Tests
norisimons/c-sharp-syllabus pull request #10
Opened 2021-08-28 16:19 UTC by norisimons

Tests finish

2021-08-29 18:51 UTC, ausmoons requested changes

2021-08-29 18:51 UTC, ausmoons commented on Tests11/Aritm1.Tests/ProgramenTests.cs
> +        public void ComparisonOfTwoNumbers_TwoNumbers_True()
IsFifteen_NumbersMake15_True

2021-08-29 18:51 UTC, ausmoons commented on Tests11/Aritm10.Tests/ProgramTests.cs
> +        public void CalculateAreaOfRectangle_AreaOfGeometry_ReturnAreaOfRectangle()
MetodesNosaukums_KoSagaida_KoPadod. Salabo visur

2021-08-29 18:51 UTC, ausmoons commented on Tests11/Aritm6.Tests/ProgramTests.cs
> +        //arrange
Te nevajag arrange komentāru

2021-08-29 18:51 UTC, ausmoons commented on Tests11/Aritm8/Program.cs
> +            }
Dažādus if varēja atdalīt ar vienu tukšu rindu

2021-08-29 18:51 UTC, ausmoons commented on Tests11/Array6.Tests/ProgramTests.cs
> +            for (var i = 0; i < actual.Length; i++)
Vai tad nav jau metodes, kas to salīdzina?

2021-08-29 18:51 UTC, ausmoons commented on Tests11/Array6.Tests/ProgramTests.cs
> +            var actual = Program.RandomArray(2);
Tev arrange un act ir vienādi. Un ja jau random..vai vispār vajag testēt..galvenais pāŗbaudīt, ka ir izveidots array, kas nav tukšs

2021-08-29 18:51 UTC, ausmoons commented on Tests11/Collect6.Tests/ProgramTests.cs
> +    public class ProgramTests
Un vispār namingam vajadzētu būt kkam labākam par oriģināli dotajiem (Programm)

2021-08-29 18:51 UTC, ausmoons commented on Tests11/Polymorp6.Tests/HierarchyTests.cs
> +        public void TigerSounTest_Tiger_TigerSoun()
MakeSound_Tiger_TigerSoun()

2021-08-29 18:51 UTC, ausmoons commented on Tests11/Testa uzdevumi/Arithmetic/CalculateArea/Program.cs
> +        public static void calculateRectangleArea()
Metodes ar lielo burtu

2021-08-29 18:51 UTC, ausmoons commented on Tests11/Testa uzdevumi/Collections/WordCount/Program.cs
> +        public static string HowLines()
HowLines? Nav saprotams kas te notiek

2021-08-29 18:51 UTC, ausmoons commented on Tests11/Testa uzdevumi/Collections/WordCount/Program.cs
> +            var text = File.ReadAllLines("../../lear.txt");
allLines un allText, nevis vnk text

2021-08-30 00:00 UTC, norisimons commented on Tests11/Aritm8/Program.cs
> +            }
Atdalīju

2021-08-30 00:11 UTC, norisimons commented on Tests11/Testa uzdevumi/Collections/WordCount/Program.cs
> +            var text = File.ReadAllLines("../../lear.txt");
Nomainīju

2021-08-30 08:03 UTC, norisimons commented on Tests11/Testa uzdevumi/Collections/WordCount/Program.cs
> +        public static string HowLines()
Nomainīju

2021-08-30 17:07 UTC, ausmoons approved these changes

2021-08-30 17:56 UTC, merged